import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
// import api from "../components/api";
import { useEffect, useState } from "react";
import nextConfig from "../next.config";
import * as Style from "../styles/home.js";

export default function Home() {
  const [pokemon, setPokemon] = useState([]);
  // const [sprites, setSprites] = useState([]);
  // const [post, setPost] = useState([]);

  // useEffect(() => {
  //   const POKE_API_URL = "https://pokeapi.co/api/v2/pokemon";
  //   fetch(POKE_API_URL)
  //     .then((serverResponse) => {
  //       return serverResponse.json();
  //     })
  //     .then((response) => {
  //       setPokemon(response.results);
  //       // setSprites(response.results.url);
  //       console.log(response.results);
  //       console.log(response.results[0].url);
  //       const poke = response.results;
  //       console.log(poke);

  //       console.log(Object.keys(poke));
  //       console.log(
  //         Object.getOwnPropertyNames(poke).forEach(function (val) {
  //           const url = poke[val].url;

  //           fetch(url)
  //             .then((spriteResponse) => {
  //               return spriteResponse.json();
  //             })
  //             .then((respons) => {
  //               setSprites(respons.sprites);
  //               console.log(respons.sprites.front_default);
  //             });
  //         })
  //       );
  //       // console.log(Object.values(poke[1]));
  //       // for (Object.getFields of poke) {
  //       //   console.log(poke);
  //       // }

  //       // console.log(response.results.key[1]);
  //       // const SPRITES_API_URL = `${pokeUrl}`;
  //     });
  // }, []);

  useEffect(() => {
    const fetchPokemon = () => {
      const getPokemonUrl = (id) => `https://pokeapi.co/api/v2/pokemon/${id}`;

      const pokemonPromises = [];

      for (let i = 1; i <= 150; i++) {
        pokemonPromises.push(
          fetch(getPokemonUrl(i)).then((response) => response.json())
        );
      }

      Promise.all(pokemonPromises).then((pokemons) => setPokemon(pokemons));
    };
    fetchPokemon();
  }, []);
  console.log(pokemon);

  // useEffect(() => {
  //   try {
  //     fetch(
  //       "https://strapi.cannect.life/api/posts?filters[$or][0][title][$contains]=CBD&filters[$or][1][content][$contains]=${filtro}&populate=categories&populate=image&populate=author"
  //     )
  //       .then((response) => {
  //         return response.json();
  //       })
  //       .then((response) => {
  //         setPost(response.data);
  //         console.log(response.data);
  //         console.log(
  //           response.data[1].attributes.image.data.attributes.formats.thumbnail
  //             .url
  //         );
  //       });
  //   } catch (error) {
  //     console.log(error);
  //   }
  // }, []);

  return (
    <div>
      <Head>
        <title>PokeApi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Hello World</h1> */}
      <h1 className={styles.title}>
        Welcome to <Link href="/">PokeApi</Link>
      </h1>
      <div>
        {/* <h1>{pokemon}</h1> */}
        <Style.pokeGrid>
          {pokemon.map(({ name, sprites }) => {
            return (
              <div className="pokeCard">
                <h1>{name}</h1>
                <div>
                  <Image
                    src={sprites?.front_default}
                    alt={name}
                    width={100}
                    height={100}
                  />
                </div>
              </div>
            );
          })}
        </Style.pokeGrid>
      </div>
    </div>
  );
}
