import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
// import api from "../components/api";
import { useEffect, useState } from "react";
import nextConfig from "../next.config";

export default function Home() {
  // const [pokemon, setPokemon] = useState([]);
  // const [sprites, setSprites] = useState([]);
  const [post, setPost] = useState([]);

  // useEffect(() => {
  //   const POKE_API_URL = "https://pokeapi.co/api/v2/pokemon";
  //   fetch(POKE_API_URL)
  //     .then((serverResponse) => {
  //       return serverResponse.json();
  //     })
  //     .then((response) => {
  //       setPokemon(response.results);
  //       // setSprites(response.results.url);
  //       console.log(response.results);
  //       console.log(response.results[0].url);
  //       const poke = response.results;
  //       console.log(poke);

  //       console.log(Object.keys(poke));
  //       console.log(
  //         Object.getOwnPropertyNames(poke).forEach(function (val) {
  //           console.log(poke[val].url);
  //           const urls = poke[val].url;

  //           fetch(urls)
  //             .then((spriteResponse) => {
  //               return spriteResponse.json();
  //             })
  //             .then((respons) => {
  //               setSprites(respons.sprites);
  //               console.log(respons.sprites.front_default);
  //             });
  //         })
  //       );
  //       // console.log(Object.values(poke[1]));
  //       // for (Object.getFields of poke) {
  //       //   console.log(poke);
  //       // }

  //       // console.log(response.results.key[1]);
  //       // const SPRITES_API_URL = `${pokeUrl}`;
  //     });
  // }, []);

  useEffect(() => {
    try {
      fetch(
        "https://strapi.cannect.life/api/posts?filters[$or][0][title][$contains]=CBD&filters[$or][1][content][$contains]=${filtro}&populate=categories&populate=image&populate=author"
      )
        .then((response) => {
          return response.json();
        })
        .then((response) => {
          setPost(response.data);
          console.log(response.data);
          console.log(
            response.data[1].attributes.image.data.attributes.formats.thumbnail
              .url
          );
        });
    } catch (error) {
      console.log(error);
    }
  }, []);

  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <div>
      <Head>
        <title>PokeApi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Hello World</h1> */}
      <h1 className={styles.title}>
        Welcome to <Link href="/">PokeApi</Link>
      </h1>
      <div>
        <h1>Checkout our Pokemons</h1>
      </div>
      <div>
        {/* <h1>{pokemon}</h1> */}
        {/* {pokemon.map(({ name, url }) => {
          return (
            <>
              <img src={sprites.front_default} alt="" />
              <h1>{name}</h1>
              <h1>{url}</h1>
            </>
          );
        })} */}
        {/* <img src={pokemon.results.sprites.front_default} alt="" /> */}
        {post.map((id, attributes) => {
          return (
            <>
              <div key={id}>
                <img
                  src={`https://strapi.cannect.life${id.attributes.image.data.attributes.formats.thumbnail.url}`}
                  alt={id.attributes.title}
                />
                <h1>{id.attributes.title}</h1>
                {/* <h1>{id.attributes.slug}</h1> */}
                <h1>Criado em: </h1>
                {<h1>{id.attributes.createdAt}</h1>}
                {/* <h1>{id.attributes.updatedAt}</h1> */}
                {/* <div>{id.attributes.content}</div> */}
                <div>
                  <h1>CRIADO POR: </h1>
                  <h1>{id.attributes.author.data.attributes.username}</h1>
                </div>
                <a href={id.attributes.slug}>Veja Mais</a>
                {/* <Image
                  src={`https://strapi.cannect.life${id.attributes.image.data.attributes.formats.thumbnail.url}`}
                  alt={id.attributes.title}
                  width={100}
                  height={100}
                /> */}
                {/* <h1>{id.attributes.categories}</h1>
                 */}
              </div>
            </>
          );
        })}
      </div>
    </div>
  );
}
